// Code generated by turbopuffer-apigen. DO NOT EDIT.

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Turbopuffer.Models.Namespaces;

[JsonConverter(typeof(AggregateByJsonConverter))]
public abstract class AggregateBy
{
    internal abstract void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options);

    public static AggregateByCount Count() => new AggregateByCount();

    public static AggregateBySum Sum(string attr) => new AggregateBySum(attr);

    public static AggregateByCountDeprecated Count(string attr) =>
        new AggregateByCountDeprecated(attr);
}

[JsonConverter(typeof(AggregateByJsonConverter))]
public sealed class AggregateByRaw(JsonElement value) : AggregateBy
{
    public JsonElement Value { get; } = value;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options) =>
        this.Value.WriteTo(writer);
}

internal sealed class AggregateByJsonConverter : JsonConverter<AggregateBy>
{
    public override bool CanConvert(Type typeToConvert) =>
        typeof(AggregateBy).IsAssignableFrom(typeToConvert);

    public override AggregateBy Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    ) => new AggregateByRaw(JsonElement.ParseValue(ref reader));

    public override void Write(
        Utf8JsonWriter writer,
        AggregateBy value,
        JsonSerializerOptions options
    ) => value.WriteJson(writer, options);
}

[JsonConverter(typeof(AggregateByJsonConverter))]
public sealed class AggregateByCount : AggregateBy
{
    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        writer.WriteStringValue("Count");
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(AggregateByJsonConverter))]
public sealed class AggregateByCountDeprecated(string attr) : AggregateBy
{
    public string Attr { get; } = attr;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        writer.WriteStringValue("Count");
        JsonSerializer.Serialize(writer, this.Attr, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(AggregateByJsonConverter))]
public sealed class AggregateBySum(string attr) : AggregateBy
{
    public string Attr { get; } = attr;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        writer.WriteStringValue("Sum");
        JsonSerializer.Serialize(writer, this.Attr, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(ExprJsonConverter))]
public abstract class Expr
{
    internal abstract void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options);

    public static ExprRefNew RefNew(string refNew) => new ExprRefNew(refNew);

    public static ExprEmbed Embed(string value) => new ExprEmbed(value);

    public static ExprEmbedWithParams Embed(string value, EmbedParams @params) =>
        new ExprEmbedWithParams(value, @params);

    public static ExprVectorDist VectorDist(
        string attr,
        System.Collections.Generic.IEnumerable<float> value
    ) => new ExprVectorDist(attr, System.Linq.Enumerable.ToArray(value));

    public static ExprHighlight Highlight(string attr) => new ExprHighlight(attr);

    public static ExprHighlightWithConfig Highlight(string attr, HighlightConfigParams config) =>
        new ExprHighlightWithConfig(attr, config);
}

[JsonConverter(typeof(ExprJsonConverter))]
public sealed class ExprRaw(JsonElement value) : Expr
{
    public JsonElement Value { get; } = value;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options) =>
        this.Value.WriteTo(writer);
}

internal sealed class ExprJsonConverter : JsonConverter<Expr>
{
    public override bool CanConvert(Type typeToConvert) =>
        typeof(Expr).IsAssignableFrom(typeToConvert);

    public override Expr Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    ) => new ExprRaw(JsonElement.ParseValue(ref reader));

    public override void Write(Utf8JsonWriter writer, Expr value, JsonSerializerOptions options) =>
        value.WriteJson(writer, options);
}

[JsonConverter(typeof(ExprJsonConverter))]
public sealed class ExprEmbed(string value) : Expr
{
    public string Value { get; } = value;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        writer.WriteStringValue("Embed");
        JsonSerializer.Serialize(writer, this.Value, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(ExprJsonConverter))]
public sealed class ExprEmbedWithParams(string value, EmbedParams @params) : Expr
{
    public string Value { get; } = value;
    public EmbedParams Params { get; } = @params;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        writer.WriteStringValue("Embed");
        JsonSerializer.Serialize(writer, this.Value, options);
        JsonSerializer.Serialize(writer, this.Params, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(ExprJsonConverter))]
public sealed class ExprHighlight(string attr) : Expr
{
    public string Attr { get; } = attr;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        writer.WriteStringValue("Highlight");
        JsonSerializer.Serialize(writer, this.Attr, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(ExprJsonConverter))]
public sealed class ExprHighlightWithConfig(string attr, HighlightConfigParams config) : Expr
{
    public string Attr { get; } = attr;
    public HighlightConfigParams Config { get; } = config;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        writer.WriteStringValue("Highlight");
        JsonSerializer.Serialize(writer, this.Attr, options);
        JsonSerializer.Serialize(writer, this.Config, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(ExprJsonConverter))]
public sealed class ExprRefNew(string refNew) : Expr
{
    public new string RefNew { get; } = refNew;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartObject();
        writer.WritePropertyName("$ref_new");
        JsonSerializer.Serialize(writer, this.RefNew, options);
        writer.WriteEndObject();
    }
}

[JsonConverter(typeof(ExprJsonConverter))]
public sealed class ExprVectorDist(string attr, float[] value) : Expr
{
    public string Attr { get; } = attr;
    public float[] Value { get; } = value;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        JsonSerializer.Serialize(writer, this.Attr, options);
        writer.WriteStringValue("VectorDist");
        JsonSerializer.Serialize(writer, this.Value, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(FilterJsonConverter))]
public abstract class Filter : RankByText
{
    public static FilterEq Eq(string attr, object value) => new FilterEq(attr, value);

    public static FilterNotEq NotEq(string attr, object value) => new FilterNotEq(attr, value);

    public static FilterIn<T> In<T>(string attr, System.Collections.Generic.IEnumerable<T> value) =>
        new FilterIn<T>(attr, System.Linq.Enumerable.ToArray(value));

    public static FilterNotIn<T> NotIn<T>(
        string attr,
        System.Collections.Generic.IEnumerable<T> value
    ) => new FilterNotIn<T>(attr, System.Linq.Enumerable.ToArray(value));

    public static FilterContains Contains(string attr, object value) =>
        new FilterContains(attr, value);

    public static FilterNotContains NotContains(string attr, object value) =>
        new FilterNotContains(attr, value);

    public static FilterContainsAny<T> ContainsAny<T>(
        string attr,
        System.Collections.Generic.IEnumerable<T> value
    ) => new FilterContainsAny<T>(attr, System.Linq.Enumerable.ToArray(value));

    public static FilterNotContainsAny<T> NotContainsAny<T>(
        string attr,
        System.Collections.Generic.IEnumerable<T> value
    ) => new FilterNotContainsAny<T>(attr, System.Linq.Enumerable.ToArray(value));

    public static FilterLt Lt(string attr, object value) => new FilterLt(attr, value);

    public static FilterLte Lte(string attr, object value) => new FilterLte(attr, value);

    public static FilterGt Gt(string attr, object value) => new FilterGt(attr, value);

    public static FilterGte Gte(string attr, object value) => new FilterGte(attr, value);

    public static FilterAnyLt AnyLt(string attr, object value) => new FilterAnyLt(attr, value);

    public static FilterAnyLte AnyLte(string attr, object value) => new FilterAnyLte(attr, value);

    public static FilterAnyGt AnyGt(string attr, object value) => new FilterAnyGt(attr, value);

    public static FilterAnyGte AnyGte(string attr, object value) => new FilterAnyGte(attr, value);

    public static FilterGlob Glob(string attr, string value) => new FilterGlob(attr, value);

    public static FilterNotGlob NotGlob(string attr, string value) =>
        new FilterNotGlob(attr, value);

    public static FilterIGlob IGlob(string attr, string value) => new FilterIGlob(attr, value);

    public static FilterNotIGlob NotIGlob(string attr, string value) =>
        new FilterNotIGlob(attr, value);

    public static FilterRegex Regex(string attr, string value) => new FilterRegex(attr, value);

    public static FilterFuzzy Fuzzy(string attr, string value, FuzzyParams @params) =>
        new FilterFuzzy(attr, value, @params);

    public static FilterContainsAllTokens ContainsAllTokens(string attr, string value) =>
        new FilterContainsAllTokens(attr, value);

    public static FilterContainsAllTokensArray ContainsAllTokens(
        string attr,
        System.Collections.Generic.IEnumerable<string> value
    ) => new FilterContainsAllTokensArray(attr, System.Linq.Enumerable.ToArray(value));

    public static FilterContainsAllTokensWithParams ContainsAllTokens(
        string attr,
        string value,
        ContainsAllTokensFilterParams @params
    ) => new FilterContainsAllTokensWithParams(attr, value, @params);

    public static FilterContainsAllTokensArrayWithParams ContainsAllTokens(
        string attr,
        System.Collections.Generic.IEnumerable<string> value,
        ContainsAllTokensFilterParams @params
    ) =>
        new FilterContainsAllTokensArrayWithParams(
            attr,
            System.Linq.Enumerable.ToArray(value),
            @params
        );

    public static FilterContainsAnyToken ContainsAnyToken(string attr, string value) =>
        new FilterContainsAnyToken(attr, value);

    public static FilterContainsAnyTokenArray ContainsAnyToken(
        string attr,
        System.Collections.Generic.IEnumerable<string> value
    ) => new FilterContainsAnyTokenArray(attr, System.Linq.Enumerable.ToArray(value));

    public static FilterContainsAnyTokenWithParams ContainsAnyToken(
        string attr,
        string value,
        ContainsAnyTokenFilterParams @params
    ) => new FilterContainsAnyTokenWithParams(attr, value, @params);

    public static FilterContainsAnyTokenArrayWithParams ContainsAnyToken(
        string attr,
        System.Collections.Generic.IEnumerable<string> value,
        ContainsAnyTokenFilterParams @params
    ) =>
        new FilterContainsAnyTokenArrayWithParams(
            attr,
            System.Linq.Enumerable.ToArray(value),
            @params
        );

    public static FilterContainsTokenSequence ContainsTokenSequence(string attr, string value) =>
        new FilterContainsTokenSequence(attr, value);

    public static FilterContainsTokenSequenceArray ContainsTokenSequence(
        string attr,
        System.Collections.Generic.IEnumerable<string> value
    ) => new FilterContainsTokenSequenceArray(attr, System.Linq.Enumerable.ToArray(value));

    public static FilterNot Not(Filter filter) => new FilterNot(filter);

    public static FilterAnd And(params Filter[] filters) => new FilterAnd(filters);

    public static FilterOr Or(params Filter[] filters) => new FilterOr(filters);
}

[JsonConverter(typeof(FilterJsonConverter))]
public sealed class FilterRaw(JsonElement value) : Filter
{
    public JsonElement Value { get; } = value;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options) =>
        this.Value.WriteTo(writer);
}

internal sealed class FilterJsonConverter : JsonConverter<Filter>
{
    public override bool CanConvert(Type typeToConvert) =>
        typeof(Filter).IsAssignableFrom(typeToConvert);

    public override Filter Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    ) => new FilterRaw(JsonElement.ParseValue(ref reader));

    public override void Write(
        Utf8JsonWriter writer,
        Filter value,
        JsonSerializerOptions options
    ) => value.WriteJson(writer, options);
}

[JsonConverter(typeof(FilterJsonConverter))]
public sealed class FilterAnd(Filter[] filters) : Filter
{
    public Filter[] Filters { get; } = filters;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        writer.WriteStringValue("And");
        JsonSerializer.Serialize(writer, this.Filters, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(FilterJsonConverter))]
public sealed class FilterAnyGt(string attr, object value) : Filter
{
    public string Attr { get; } = attr;
    public object Value { get; } = value;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        JsonSerializer.Serialize(writer, this.Attr, options);
        writer.WriteStringValue("AnyGt");
        JsonSerializer.Serialize(writer, this.Value, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(FilterJsonConverter))]
public sealed class FilterAnyGte(string attr, object value) : Filter
{
    public string Attr { get; } = attr;
    public object Value { get; } = value;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        JsonSerializer.Serialize(writer, this.Attr, options);
        writer.WriteStringValue("AnyGte");
        JsonSerializer.Serialize(writer, this.Value, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(FilterJsonConverter))]
public sealed class FilterAnyLt(string attr, object value) : Filter
{
    public string Attr { get; } = attr;
    public object Value { get; } = value;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        JsonSerializer.Serialize(writer, this.Attr, options);
        writer.WriteStringValue("AnyLt");
        JsonSerializer.Serialize(writer, this.Value, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(FilterJsonConverter))]
public sealed class FilterAnyLte(string attr, object value) : Filter
{
    public string Attr { get; } = attr;
    public object Value { get; } = value;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        JsonSerializer.Serialize(writer, this.Attr, options);
        writer.WriteStringValue("AnyLte");
        JsonSerializer.Serialize(writer, this.Value, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(FilterJsonConverter))]
public sealed class FilterContains(string attr, object value) : Filter
{
    public string Attr { get; } = attr;
    public object Value { get; } = value;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        JsonSerializer.Serialize(writer, this.Attr, options);
        writer.WriteStringValue("Contains");
        JsonSerializer.Serialize(writer, this.Value, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(FilterJsonConverter))]
public sealed class FilterContainsAllTokens(string attr, string value) : Filter
{
    public string Attr { get; } = attr;
    public string Value { get; } = value;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        JsonSerializer.Serialize(writer, this.Attr, options);
        writer.WriteStringValue("ContainsAllTokens");
        JsonSerializer.Serialize(writer, this.Value, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(FilterJsonConverter))]
public sealed class FilterContainsAllTokensArray(string attr, string[] value) : Filter
{
    public string Attr { get; } = attr;
    public string[] Value { get; } = value;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        JsonSerializer.Serialize(writer, this.Attr, options);
        writer.WriteStringValue("ContainsAllTokens");
        JsonSerializer.Serialize(writer, this.Value, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(FilterJsonConverter))]
public sealed class FilterContainsAllTokensArrayWithParams(
    string attr,
    string[] value,
    ContainsAllTokensFilterParams @params
) : Filter
{
    public string Attr { get; } = attr;
    public string[] Value { get; } = value;
    public ContainsAllTokensFilterParams Params { get; } = @params;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        JsonSerializer.Serialize(writer, this.Attr, options);
        writer.WriteStringValue("ContainsAllTokens");
        JsonSerializer.Serialize(writer, this.Value, options);
        JsonSerializer.Serialize(writer, this.Params, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(FilterJsonConverter))]
public sealed class FilterContainsAllTokensWithParams(
    string attr,
    string value,
    ContainsAllTokensFilterParams @params
) : Filter
{
    public string Attr { get; } = attr;
    public string Value { get; } = value;
    public ContainsAllTokensFilterParams Params { get; } = @params;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        JsonSerializer.Serialize(writer, this.Attr, options);
        writer.WriteStringValue("ContainsAllTokens");
        JsonSerializer.Serialize(writer, this.Value, options);
        JsonSerializer.Serialize(writer, this.Params, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(FilterJsonConverter))]
public sealed class FilterContainsAny<T>(string attr, T[] value) : Filter
{
    public string Attr { get; } = attr;
    public T[] Value { get; } = value;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        JsonSerializer.Serialize(writer, this.Attr, options);
        writer.WriteStringValue("ContainsAny");
        JsonSerializer.Serialize(writer, this.Value, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(FilterJsonConverter))]
public sealed class FilterContainsAnyToken(string attr, string value) : Filter
{
    public string Attr { get; } = attr;
    public string Value { get; } = value;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        JsonSerializer.Serialize(writer, this.Attr, options);
        writer.WriteStringValue("ContainsAnyToken");
        JsonSerializer.Serialize(writer, this.Value, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(FilterJsonConverter))]
public sealed class FilterContainsAnyTokenArray(string attr, string[] value) : Filter
{
    public string Attr { get; } = attr;
    public string[] Value { get; } = value;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        JsonSerializer.Serialize(writer, this.Attr, options);
        writer.WriteStringValue("ContainsAnyToken");
        JsonSerializer.Serialize(writer, this.Value, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(FilterJsonConverter))]
public sealed class FilterContainsAnyTokenArrayWithParams(
    string attr,
    string[] value,
    ContainsAnyTokenFilterParams @params
) : Filter
{
    public string Attr { get; } = attr;
    public string[] Value { get; } = value;
    public ContainsAnyTokenFilterParams Params { get; } = @params;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        JsonSerializer.Serialize(writer, this.Attr, options);
        writer.WriteStringValue("ContainsAnyToken");
        JsonSerializer.Serialize(writer, this.Value, options);
        JsonSerializer.Serialize(writer, this.Params, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(FilterJsonConverter))]
public sealed class FilterContainsAnyTokenWithParams(
    string attr,
    string value,
    ContainsAnyTokenFilterParams @params
) : Filter
{
    public string Attr { get; } = attr;
    public string Value { get; } = value;
    public ContainsAnyTokenFilterParams Params { get; } = @params;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        JsonSerializer.Serialize(writer, this.Attr, options);
        writer.WriteStringValue("ContainsAnyToken");
        JsonSerializer.Serialize(writer, this.Value, options);
        JsonSerializer.Serialize(writer, this.Params, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(FilterJsonConverter))]
public sealed class FilterContainsTokenSequence(string attr, string value) : Filter
{
    public string Attr { get; } = attr;
    public string Value { get; } = value;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        JsonSerializer.Serialize(writer, this.Attr, options);
        writer.WriteStringValue("ContainsTokenSequence");
        JsonSerializer.Serialize(writer, this.Value, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(FilterJsonConverter))]
public sealed class FilterContainsTokenSequenceArray(string attr, string[] value) : Filter
{
    public string Attr { get; } = attr;
    public string[] Value { get; } = value;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        JsonSerializer.Serialize(writer, this.Attr, options);
        writer.WriteStringValue("ContainsTokenSequence");
        JsonSerializer.Serialize(writer, this.Value, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(FilterJsonConverter))]
public sealed class FilterEq(string attr, object value) : Filter
{
    public string Attr { get; } = attr;
    public object Value { get; } = value;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        JsonSerializer.Serialize(writer, this.Attr, options);
        writer.WriteStringValue("Eq");
        JsonSerializer.Serialize(writer, this.Value, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(FilterJsonConverter))]
public sealed class FilterFuzzy(string attr, string value, FuzzyParams @params) : Filter
{
    public string Attr { get; } = attr;
    public string Value { get; } = value;
    public FuzzyParams Params { get; } = @params;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        JsonSerializer.Serialize(writer, this.Attr, options);
        writer.WriteStringValue("Fuzzy");
        JsonSerializer.Serialize(writer, this.Value, options);
        JsonSerializer.Serialize(writer, this.Params, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(FilterJsonConverter))]
public sealed class FilterGlob(string attr, string value) : Filter
{
    public string Attr { get; } = attr;
    public string Value { get; } = value;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        JsonSerializer.Serialize(writer, this.Attr, options);
        writer.WriteStringValue("Glob");
        JsonSerializer.Serialize(writer, this.Value, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(FilterJsonConverter))]
public sealed class FilterGt(string attr, object value) : Filter
{
    public string Attr { get; } = attr;
    public object Value { get; } = value;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        JsonSerializer.Serialize(writer, this.Attr, options);
        writer.WriteStringValue("Gt");
        JsonSerializer.Serialize(writer, this.Value, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(FilterJsonConverter))]
public sealed class FilterGte(string attr, object value) : Filter
{
    public string Attr { get; } = attr;
    public object Value { get; } = value;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        JsonSerializer.Serialize(writer, this.Attr, options);
        writer.WriteStringValue("Gte");
        JsonSerializer.Serialize(writer, this.Value, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(FilterJsonConverter))]
public sealed class FilterIGlob(string attr, string value) : Filter
{
    public string Attr { get; } = attr;
    public string Value { get; } = value;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        JsonSerializer.Serialize(writer, this.Attr, options);
        writer.WriteStringValue("IGlob");
        JsonSerializer.Serialize(writer, this.Value, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(FilterJsonConverter))]
public sealed class FilterIn<T>(string attr, T[] value) : Filter
{
    public string Attr { get; } = attr;
    public T[] Value { get; } = value;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        JsonSerializer.Serialize(writer, this.Attr, options);
        writer.WriteStringValue("In");
        JsonSerializer.Serialize(writer, this.Value, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(FilterJsonConverter))]
public sealed class FilterLt(string attr, object value) : Filter
{
    public string Attr { get; } = attr;
    public object Value { get; } = value;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        JsonSerializer.Serialize(writer, this.Attr, options);
        writer.WriteStringValue("Lt");
        JsonSerializer.Serialize(writer, this.Value, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(FilterJsonConverter))]
public sealed class FilterLte(string attr, object value) : Filter
{
    public string Attr { get; } = attr;
    public object Value { get; } = value;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        JsonSerializer.Serialize(writer, this.Attr, options);
        writer.WriteStringValue("Lte");
        JsonSerializer.Serialize(writer, this.Value, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(FilterJsonConverter))]
public sealed class FilterNot(Filter filter) : Filter
{
    public Filter Filter { get; } = filter;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        writer.WriteStringValue("Not");
        JsonSerializer.Serialize(writer, this.Filter, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(FilterJsonConverter))]
public sealed class FilterNotContains(string attr, object value) : Filter
{
    public string Attr { get; } = attr;
    public object Value { get; } = value;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        JsonSerializer.Serialize(writer, this.Attr, options);
        writer.WriteStringValue("NotContains");
        JsonSerializer.Serialize(writer, this.Value, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(FilterJsonConverter))]
public sealed class FilterNotContainsAny<T>(string attr, T[] value) : Filter
{
    public string Attr { get; } = attr;
    public T[] Value { get; } = value;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        JsonSerializer.Serialize(writer, this.Attr, options);
        writer.WriteStringValue("NotContainsAny");
        JsonSerializer.Serialize(writer, this.Value, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(FilterJsonConverter))]
public sealed class FilterNotEq(string attr, object value) : Filter
{
    public string Attr { get; } = attr;
    public object Value { get; } = value;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        JsonSerializer.Serialize(writer, this.Attr, options);
        writer.WriteStringValue("NotEq");
        JsonSerializer.Serialize(writer, this.Value, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(FilterJsonConverter))]
public sealed class FilterNotGlob(string attr, string value) : Filter
{
    public string Attr { get; } = attr;
    public string Value { get; } = value;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        JsonSerializer.Serialize(writer, this.Attr, options);
        writer.WriteStringValue("NotGlob");
        JsonSerializer.Serialize(writer, this.Value, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(FilterJsonConverter))]
public sealed class FilterNotIGlob(string attr, string value) : Filter
{
    public string Attr { get; } = attr;
    public string Value { get; } = value;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        JsonSerializer.Serialize(writer, this.Attr, options);
        writer.WriteStringValue("NotIGlob");
        JsonSerializer.Serialize(writer, this.Value, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(FilterJsonConverter))]
public sealed class FilterNotIn<T>(string attr, T[] value) : Filter
{
    public string Attr { get; } = attr;
    public T[] Value { get; } = value;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        JsonSerializer.Serialize(writer, this.Attr, options);
        writer.WriteStringValue("NotIn");
        JsonSerializer.Serialize(writer, this.Value, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(FilterJsonConverter))]
public sealed class FilterOr(Filter[] filters) : Filter
{
    public Filter[] Filters { get; } = filters;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        writer.WriteStringValue("Or");
        JsonSerializer.Serialize(writer, this.Filters, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(FilterJsonConverter))]
public sealed class FilterRegex(string attr, string value) : Filter
{
    public string Attr { get; } = attr;
    public string Value { get; } = value;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        JsonSerializer.Serialize(writer, this.Attr, options);
        writer.WriteStringValue("Regex");
        JsonSerializer.Serialize(writer, this.Value, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(GroupByJsonConverter))]
public abstract class GroupBy
{
    internal abstract void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options);

    public static GroupByAttr Attr(string value) => new GroupByAttr(value);

    public static GroupByExpr Expr(string name, GroupByFunction value) =>
        new GroupByExpr(name, value);
}

[JsonConverter(typeof(GroupByJsonConverter))]
public sealed class GroupByRaw(JsonElement value) : GroupBy
{
    public JsonElement Value { get; } = value;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options) =>
        this.Value.WriteTo(writer);
}

internal sealed class GroupByJsonConverter : JsonConverter<GroupBy>
{
    public override bool CanConvert(Type typeToConvert) =>
        typeof(GroupBy).IsAssignableFrom(typeToConvert);

    public override GroupBy Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    ) => new GroupByRaw(JsonElement.ParseValue(ref reader));

    public override void Write(
        Utf8JsonWriter writer,
        GroupBy value,
        JsonSerializerOptions options
    ) => value.WriteJson(writer, options);
}

[JsonConverter(typeof(GroupByJsonConverter))]
public sealed class GroupByAttr(string value) : GroupBy
{
    public string Value { get; } = value;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStringValue(this.Value);
    }
}

[JsonConverter(typeof(GroupByJsonConverter))]
public sealed class GroupByExpr(string name, GroupByFunction value) : GroupBy
{
    public string Name { get; } = name;
    public GroupByFunction Value { get; } = value;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartObject();
        writer.WritePropertyName(this.Name);
        JsonSerializer.Serialize(writer, this.Value, options);
        writer.WriteEndObject();
    }
}

[JsonConverter(typeof(GroupByFunctionJsonConverter))]
public abstract class GroupByFunction
{
    internal abstract void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options);

    public static GroupByFunctionForEachUnique ForEachUnique(string attr) =>
        new GroupByFunctionForEachUnique(attr);
}

[JsonConverter(typeof(GroupByFunctionJsonConverter))]
public sealed class GroupByFunctionRaw(JsonElement value) : GroupByFunction
{
    public JsonElement Value { get; } = value;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options) =>
        this.Value.WriteTo(writer);
}

internal sealed class GroupByFunctionJsonConverter : JsonConverter<GroupByFunction>
{
    public override bool CanConvert(Type typeToConvert) =>
        typeof(GroupByFunction).IsAssignableFrom(typeToConvert);

    public override GroupByFunction Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    ) => new GroupByFunctionRaw(JsonElement.ParseValue(ref reader));

    public override void Write(
        Utf8JsonWriter writer,
        GroupByFunction value,
        JsonSerializerOptions options
    ) => value.WriteJson(writer, options);
}

[JsonConverter(typeof(GroupByFunctionJsonConverter))]
public sealed class GroupByFunctionForEachUnique(string attr) : GroupByFunction
{
    public string Attr { get; } = attr;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        writer.WriteStringValue("ForEachUnique");
        JsonSerializer.Serialize(writer, this.Attr, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(RankByJsonConverter))]
public abstract class RankBy : Expr
{
    public static RankByAnn Ann(string attr, System.Collections.Generic.IEnumerable<float> value) =>
        new RankByAnn(attr, System.Linq.Enumerable.ToArray(value));

    public static RankByAnnMulti Ann(
        string attr,
        System.Collections.Generic.IEnumerable<float[]> value
    ) => new RankByAnnMulti(attr, System.Linq.Enumerable.ToArray(value));

    public static RankByAnnExpr Ann(string attr, Expr expr) => new RankByAnnExpr(attr, expr);

    public static RankByKnn Knn(string attr, System.Collections.Generic.IEnumerable<float> value) =>
        new RankByKnn(attr, System.Linq.Enumerable.ToArray(value));

    public static RankByKnnMulti Knn(
        string attr,
        System.Collections.Generic.IEnumerable<float[]> value
    ) => new RankByKnnMulti(attr, System.Linq.Enumerable.ToArray(value));

    public static RankByKnnExpr Knn(string attr, Expr expr) => new RankByKnnExpr(attr, expr);

    public static RankBySparseKnn SparseKnn(
        string attr,
        System.Collections.Generic.IReadOnlyDictionary<string, double> value
    ) => new RankBySparseKnn(attr, value);

    public static RankByAttribute Attribute(string attr, RankByAttributeOrder order) =>
        new RankByAttribute(attr, order);

    public static RankByAttributes Attributes(params RankByAttribute[] items) =>
        new RankByAttributes(items);
}

[JsonConverter(typeof(RankByJsonConverter))]
public sealed class RankByRaw(JsonElement value) : RankBy
{
    public JsonElement Value { get; } = value;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options) =>
        this.Value.WriteTo(writer);
}

internal sealed class RankByJsonConverter : JsonConverter<RankBy>
{
    public override bool CanConvert(Type typeToConvert) =>
        typeof(RankBy).IsAssignableFrom(typeToConvert);

    public override RankBy Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    ) => new RankByRaw(JsonElement.ParseValue(ref reader));

    public override void Write(
        Utf8JsonWriter writer,
        RankBy value,
        JsonSerializerOptions options
    ) => value.WriteJson(writer, options);
}

[JsonConverter(typeof(RankByJsonConverter))]
public sealed class RankByAnn(string attr, float[] value) : RankBy
{
    public string Attr { get; } = attr;
    public float[] Value { get; } = value;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        JsonSerializer.Serialize(writer, this.Attr, options);
        writer.WriteStringValue("ANN");
        JsonSerializer.Serialize(writer, this.Value, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(RankByJsonConverter))]
public sealed class RankByAnnExpr(string attr, Expr expr) : RankBy
{
    public string Attr { get; } = attr;
    public Expr Expr { get; } = expr;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        JsonSerializer.Serialize(writer, this.Attr, options);
        writer.WriteStringValue("ANN");
        JsonSerializer.Serialize(writer, this.Expr, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(RankByJsonConverter))]
public sealed class RankByAnnMulti(string attr, float[][] value) : RankBy
{
    public string Attr { get; } = attr;
    public float[][] Value { get; } = value;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        JsonSerializer.Serialize(writer, this.Attr, options);
        writer.WriteStringValue("ANN");
        JsonSerializer.Serialize(writer, this.Value, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(RankByJsonConverter))]
public sealed class RankByAttribute(string attr, RankByAttributeOrder order) : RankBy
{
    public string Attr { get; } = attr;
    public RankByAttributeOrder Order { get; } = order;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        JsonSerializer.Serialize(writer, this.Attr, options);
        JsonSerializer.Serialize(writer, this.Order, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(RankByAttributeOrderJsonConverter))]
public enum RankByAttributeOrder
{
    ASC,
    DESC,
}

internal sealed class RankByAttributeOrderJsonConverter : JsonConverter<RankByAttributeOrder>
{
    public override RankByAttributeOrder Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    ) =>
        reader.GetString() switch
        {
            "asc" => RankByAttributeOrder.ASC,
            "desc" => RankByAttributeOrder.DESC,
            var s => throw new JsonException($"Unknown RankByAttributeOrder value: {s}"),
        };

    public override void Write(
        Utf8JsonWriter writer,
        RankByAttributeOrder value,
        JsonSerializerOptions options
    ) =>
        writer.WriteStringValue(
            value switch
            {
                RankByAttributeOrder.ASC => "asc",
                RankByAttributeOrder.DESC => "desc",
                _ => throw new JsonException($"Unknown RankByAttributeOrder value: {value}"),
            }
        );
}

[JsonConverter(typeof(RankByJsonConverter))]
public sealed class RankByAttributes(RankByAttribute[] items) : RankBy
{
    public RankByAttribute[] Items { get; } = items;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        foreach (var item in this.Items)
        {
            JsonSerializer.Serialize(writer, item, options);
        }
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(RankByJsonConverter))]
public sealed class RankByKnn(string attr, float[] value) : RankBy
{
    public string Attr { get; } = attr;
    public float[] Value { get; } = value;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        JsonSerializer.Serialize(writer, this.Attr, options);
        writer.WriteStringValue("kNN");
        JsonSerializer.Serialize(writer, this.Value, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(RankByJsonConverter))]
public sealed class RankByKnnExpr(string attr, Expr expr) : RankBy
{
    public string Attr { get; } = attr;
    public Expr Expr { get; } = expr;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        JsonSerializer.Serialize(writer, this.Attr, options);
        writer.WriteStringValue("kNN");
        JsonSerializer.Serialize(writer, this.Expr, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(RankByJsonConverter))]
public sealed class RankByKnnMulti(string attr, float[][] value) : RankBy
{
    public string Attr { get; } = attr;
    public float[][] Value { get; } = value;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        JsonSerializer.Serialize(writer, this.Attr, options);
        writer.WriteStringValue("kNN");
        JsonSerializer.Serialize(writer, this.Value, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(RankByJsonConverter))]
public sealed class RankBySparseKnn(
    string attr,
    System.Collections.Generic.IReadOnlyDictionary<string, double> value
) : RankBy
{
    public string Attr { get; } = attr;
    public System.Collections.Generic.IReadOnlyDictionary<string, double> Value { get; } = value;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        JsonSerializer.Serialize(writer, this.Attr, options);
        writer.WriteStringValue("SparseKNN");
        JsonSerializer.Serialize(writer, this.Value, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(RankByTextJsonConverter))]
public abstract class RankByText : RankBy
{
    public static RankByTextBM25 BM25(string attr, string value) => new RankByTextBM25(attr, value);

    public static RankByTextBM25Array BM25(
        string attr,
        System.Collections.Generic.IEnumerable<string> value
    ) => new RankByTextBM25Array(attr, System.Linq.Enumerable.ToArray(value));

    public static RankByTextBM25WithParams BM25(
        string attr,
        string value,
        Bm25ClauseParams @params
    ) => new RankByTextBM25WithParams(attr, value, @params);

    public static RankByTextBM25ArrayWithParams BM25(
        string attr,
        System.Collections.Generic.IEnumerable<string> value,
        Bm25ClauseParams @params
    ) => new RankByTextBM25ArrayWithParams(attr, System.Linq.Enumerable.ToArray(value), @params);

    public static RankByTextSum Sum(params RankByText[] subqueries) =>
        new RankByTextSum(subqueries);

    public static RankByTextMax Max(params RankByText[] subqueries) =>
        new RankByTextMax(subqueries);

    public static RankByTextProduct Product(double weight, RankByText subquery) =>
        new RankByTextProduct(weight, subquery);

    public static RankByTextProduct2 Product(RankByText subquery, double weight) =>
        new RankByTextProduct2(subquery, weight);

    public static RankByTextAttribute Attribute(string attr) => new RankByTextAttribute(attr);

    public static RankByTextSaturate Saturate(RankByText subquery, SaturateParams @params) =>
        new RankByTextSaturate(subquery, @params);

    public static RankByTextDecay Decay(RankByText subquery, DecayParams @params) =>
        new RankByTextDecay(subquery, @params);

    public static RankByTextDist Dist(RankByText subquery, object origin) =>
        new RankByTextDist(subquery, origin);
}

[JsonConverter(typeof(RankByTextJsonConverter))]
public sealed class RankByTextRaw(JsonElement value) : RankByText
{
    public JsonElement Value { get; } = value;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options) =>
        this.Value.WriteTo(writer);
}

internal sealed class RankByTextJsonConverter : JsonConverter<RankByText>
{
    public override bool CanConvert(Type typeToConvert) =>
        typeof(RankByText).IsAssignableFrom(typeToConvert);

    public override RankByText Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    ) => new RankByTextRaw(JsonElement.ParseValue(ref reader));

    public override void Write(
        Utf8JsonWriter writer,
        RankByText value,
        JsonSerializerOptions options
    ) => value.WriteJson(writer, options);
}

[JsonConverter(typeof(RankByTextJsonConverter))]
public sealed class RankByTextAttribute(string attr) : RankByText
{
    public string Attr { get; } = attr;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        writer.WriteStringValue("Attribute");
        JsonSerializer.Serialize(writer, this.Attr, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(RankByTextJsonConverter))]
public sealed class RankByTextBM25(string attr, string value) : RankByText
{
    public string Attr { get; } = attr;
    public string Value { get; } = value;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        JsonSerializer.Serialize(writer, this.Attr, options);
        writer.WriteStringValue("BM25");
        JsonSerializer.Serialize(writer, this.Value, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(RankByTextJsonConverter))]
public sealed class RankByTextBM25Array(string attr, string[] value) : RankByText
{
    public string Attr { get; } = attr;
    public string[] Value { get; } = value;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        JsonSerializer.Serialize(writer, this.Attr, options);
        writer.WriteStringValue("BM25");
        JsonSerializer.Serialize(writer, this.Value, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(RankByTextJsonConverter))]
public sealed class RankByTextBM25ArrayWithParams(
    string attr,
    string[] value,
    Bm25ClauseParams @params
) : RankByText
{
    public string Attr { get; } = attr;
    public string[] Value { get; } = value;
    public Bm25ClauseParams Params { get; } = @params;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        JsonSerializer.Serialize(writer, this.Attr, options);
        writer.WriteStringValue("BM25");
        JsonSerializer.Serialize(writer, this.Value, options);
        JsonSerializer.Serialize(writer, this.Params, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(RankByTextJsonConverter))]
public sealed class RankByTextBM25WithParams(string attr, string value, Bm25ClauseParams @params)
    : RankByText
{
    public string Attr { get; } = attr;
    public string Value { get; } = value;
    public Bm25ClauseParams Params { get; } = @params;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        JsonSerializer.Serialize(writer, this.Attr, options);
        writer.WriteStringValue("BM25");
        JsonSerializer.Serialize(writer, this.Value, options);
        JsonSerializer.Serialize(writer, this.Params, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(RankByTextJsonConverter))]
public sealed class RankByTextDecay(RankByText subquery, DecayParams @params) : RankByText
{
    public RankByText Subquery { get; } = subquery;
    public DecayParams Params { get; } = @params;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        writer.WriteStringValue("Decay");
        JsonSerializer.Serialize(writer, this.Subquery, options);
        JsonSerializer.Serialize(writer, this.Params, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(RankByTextJsonConverter))]
public sealed class RankByTextDist(RankByText subquery, object origin) : RankByText
{
    public RankByText Subquery { get; } = subquery;
    public object Origin { get; } = origin;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        writer.WriteStringValue("Dist");
        JsonSerializer.Serialize(writer, this.Subquery, options);
        JsonSerializer.Serialize(writer, this.Origin, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(RankByTextJsonConverter))]
public sealed class RankByTextMax(RankByText[] subqueries) : RankByText
{
    public RankByText[] Subqueries { get; } = subqueries;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        writer.WriteStringValue("Max");
        JsonSerializer.Serialize(writer, this.Subqueries, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(RankByTextJsonConverter))]
public sealed class RankByTextProduct(double weight, RankByText subquery) : RankByText
{
    public double Weight { get; } = weight;
    public RankByText Subquery { get; } = subquery;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        writer.WriteStringValue("Product");
        JsonSerializer.Serialize(writer, this.Weight, options);
        JsonSerializer.Serialize(writer, this.Subquery, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(RankByTextJsonConverter))]
public sealed class RankByTextProduct2(RankByText subquery, double weight) : RankByText
{
    public RankByText Subquery { get; } = subquery;
    public double Weight { get; } = weight;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        writer.WriteStringValue("Product");
        JsonSerializer.Serialize(writer, this.Subquery, options);
        JsonSerializer.Serialize(writer, this.Weight, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(RankByTextJsonConverter))]
public sealed class RankByTextSaturate(RankByText subquery, SaturateParams @params) : RankByText
{
    public RankByText Subquery { get; } = subquery;
    public SaturateParams Params { get; } = @params;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        writer.WriteStringValue("Saturate");
        JsonSerializer.Serialize(writer, this.Subquery, options);
        JsonSerializer.Serialize(writer, this.Params, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(RankByTextJsonConverter))]
public sealed class RankByTextSum(RankByText[] subqueries) : RankByText
{
    public RankByText[] Subqueries { get; } = subqueries;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        writer.WriteStringValue("Sum");
        JsonSerializer.Serialize(writer, this.Subqueries, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(RerankByJsonConverter))]
public abstract class RerankBy
{
    internal abstract void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options);

    public static RerankByRrf Rrf() => new RerankByRrf();

    public static RerankByRrfWithParams Rrf(RrfParams f1) => new RerankByRrfWithParams(f1);
}

[JsonConverter(typeof(RerankByJsonConverter))]
public sealed class RerankByRaw(JsonElement value) : RerankBy
{
    public JsonElement Value { get; } = value;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options) =>
        this.Value.WriteTo(writer);
}

internal sealed class RerankByJsonConverter : JsonConverter<RerankBy>
{
    public override bool CanConvert(Type typeToConvert) =>
        typeof(RerankBy).IsAssignableFrom(typeToConvert);

    public override RerankBy Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    ) => new RerankByRaw(JsonElement.ParseValue(ref reader));

    public override void Write(
        Utf8JsonWriter writer,
        RerankBy value,
        JsonSerializerOptions options
    ) => value.WriteJson(writer, options);
}

[JsonConverter(typeof(RerankByJsonConverter))]
public sealed class RerankByRrf : RerankBy
{
    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        writer.WriteStringValue("RRF");
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(RerankByJsonConverter))]
public sealed class RerankByRrfWithParams(RrfParams f1) : RerankBy
{
    public RrfParams F1 { get; } = f1;

    internal override void WriteJson(Utf8JsonWriter writer, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        writer.WriteStringValue("RRF");
        JsonSerializer.Serialize(writer, this.F1, options);
        writer.WriteEndArray();
    }
}
