#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

apigen_image=ghcr.io/turbopuffer/turbopuffer-apigen:2192ac2bee58ec786b0f0b74bbd0840cff7a7937

apigen() {
    if [[ "$TURBOPUFFER_DEV_APIGEN" ]]; then
        cargo run --manifest-path=../turbopuffer-apigen/Cargo.toml "$@"
    else
        docker run -v "$(pwd):/work" "$apigen_image" "$@"
    fi
}

echo "==> Generating code"
apigen c-sharp > src/Turbopuffer/Models/Namespaces/CustomTypes.cs
scripts/format
