#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

apigen_image=ghcr.io/turbopuffer/turbopuffer-apigen:18b138f122efb885778c5b00b017c835c9e64693

apigen() {
    if [[ "$TURBOPUFFER_DEV_APIGEN" ]]; then
        cargo run --manifest-path=../turbopuffer-apigen/Cargo.toml "$@"
    else
        docker run -v "$(pwd):/work" "$apigen_image" "$@"
    fi
}

echo "==> Generating code"
apigen c-sharp > src/Turbopuffer/Models/Namespaces/CustomTypes.cs
scripts/format
